version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: equipment_counting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_equip.sql:/docker-entrypoint-initequipdb.d/init_equip.sql

volumes:
  postgres_data: